### ISSUE TITLE
Better frequencies for better predictions

### ISSUE THREAD

**Issue by pearapple123** [pearapple123/rime-hoisanva#1]
Frequency analysis of written Taishanese in progress

**Comment by suspiciouscactus** [comment]
It will be some time before we get good Taishanese frequency. We can also consider converting our existing Cantonese word frequencies to Taishanese equivalents for the time being.

**Comment by pearapple123** [comment]
Already using frequencies from rime-cantonese jyut6ping3.schema, but it looks unlikely that we will get enough frequency data for Taishanese to be usuable for the IME.
