### ISSUE TITLE
README.md in Hoisanva

### ISSUE THREAD

**Issue by suspiciouscactus** [pearapple123/rime-hoisanva#8]
rime-cantonese has docs in Cantonese. Perhaps we should do something similar. We can [eat our own dogfood](https://en.wikipedia.org/wiki/Eating_your_own_dog_food) by using our IME.

**Comment by pearapple123** [comment]
I was thinking on the same lines.

**Comment by pearapple123** [comment]
Due to a lack of translation support, I will have to close this unless a Taishanese speaker is willing to provide.
